service: ssrserverless-angular

plugins:
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  timeout: 30
  stage: production
  region: us-east-1

package:
  exclude:
   - src/**
   - node_modules/**
   - e2e/**
   - coverage/**
   - venv/**
   - .vscode
   - .angular
   - .serverless
custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  api:
    handler: lambda.ssrserverless
    events:
      - http: ANY {proxy+}
      - http: ANY /